name: Terraform pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'bookstore_backend/**'   

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bookstore_backend

    environment:
      name: production 
      url: https://bookstore.jresume.cloud  # Optional, adjust if needed


    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply (with confirmation)
      run: terraform apply -auto-approve
