name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'bookstore_frontend/**'

jobs:
  deploy:
    name: Deploy React App to S3
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bookstore_frontend

    environment:
      name: production 
      url: https://bookstore.jresume.cloud  # Optional, adjust if needed    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create .env.production file
        run: |
          echo "REACT_APP_API_URI_UPLOAD=${{ secrets.REACT_APP_API_URI_UPLOAD }}" >> .env.production
          echo "REACT_APP_API_URI_DOWNLOAD=${{ secrets.REACT_APP_API_URI_DOWNLOAD }}" >> .env.production
          echo "REACT_APP_API_URI_SEARCH=${{ secrets.REACT_APP_API_URI_SEARCH }}" >> .env.production    

      - name: Build React App
        run: npm run build
        
      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
